server:
  port: 8090



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu_reg?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  profiles:
#    active: dev
#logging:
#  level:
#    root: error
